### ISSUE TITLE
issues about extracting enclosing subgraph

### ISSUE THREAD

**Issue by smart-lty** [kkteru/grail#9]
![image](https://user-images.githubusercontent.com/55835956/152716627-8f4febf7-f276-4a29-9797-556d4747c077.png)
I would like to ask why the nodes 3 and 4 are removed? They are both at  a distance (undirected) of 2 from nodes 1 and 2.

**Comment by kkteru** [comment]
Hi,

Thanks for bringing this up. There is a slight error in the description of the steps. In order to remove the nodes 3 and 4, we do an additional pruning step where we remove nodes with d(i, u) + d(i, v) > k + 1. This step is essential not only for the case you brought up but also to make sure we only have paths of length of at most k + 1. In the code, this pruning is applied [here](https://github.com/kkteru/grail/blob/2a3dffa719518e7e6250e355a2fb37cd932de91e/subgraph_extraction/graph_sampler.py#L224). 

However, without this additional pruning, you would still get all paths of length k + 1 (albeit with some additional noise).

Hope that helps.

**Comment by smart-lty** [comment]
Thanks a lot! I totally understand it. However, in the code, the pruning process is `enclosing_subgraph_nodes = np.where(np.max(labels, axis=1) <= max_distance)[0]`, which is equivalent to max( d(i, u) , d(i, v) ) <= k. I have not seen the process of removing nodes with d(i, u) + d(i, v) > k + 1. Does the code need some justification?

**Comment by kkteru** [comment]
Yes, the current code as it is does not apply this additional step. The results in the paper are obtained with the code in this repository, i.e., with the additional noise that you pointed out. For reproducibility of the numbers published in the paper, we do not change the code as such. This should be a fairly easy addition though. It has been a while but we did some quick experiments with this modification and did not see any significant drop in the performance.

I would be happy to accept a PR in case you want to run these experiments and report the results in the README.

**Comment by smart-lty** [comment]
Thanks for your patient answers!
*.。(๑･∀･๑)*.。
